version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    networks:
      - frontend
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile.webapp
    depends_on:
      - api
    networks:
      - frontend
  gateway:
    build: 
      context: ./gateway
      dockerfile: ./Dockerfile.gateway
    ports:
      - "80:80"
    depends_on:
      - webapp
      - api
    volumes:
      - "./gateway/nginx_lua/:/opt/app/"
      - "./gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    networks:
      - frontend
  selenium_runner:
    image: selenium/standalone-firefox:4.1.3-20220405
    shm_size: '2gb'
    ports:
      - "4444:4444"
    depends_on:
      - webapp
    networks:
      - frontend
    extra_hosts:
      - "bus-homework.example:host-gateway"
networks:
  frontend: